// Placeholder generated by @msamblanet/node-project-template

import { loadedTime } from './index.js';

console.log(loadedTime);

// All ESM modules are required to have some default export...
const defaultExport = {};
export default defaultExport;
